SamarthTMSL/Python-Games-and-Projects

snake_game/README.md
snake_game/snake-game.py

I've added the classic snake game created using pygame in Python.

Added Snake Game in Python

---

Calculator/jumblegame.py

added jumblegame.py

---

Number Guessing By The User/number_guessing_by_the_user.py

I create **Number Guessing By The User** game and _**tested many times**_.
It **works perfectly**.
-Thank You.

I create Number Guessing By The User game

---

2022_GFX_Shape/shape.py

Gfx Shapes

---

2022_GFX_Shape/shape.py
2022_Tic_Tac_Toe/Tic.py

Tic tak toc

---

2022_GFX_Shape/shape.py
2022_Rock_Paper_Scissor/rock_paper.py
2022_Tic_Tac_Toe/Tic.py

Stone Paper Scissors game using python

Stone paper scissors

---

News Updater/News.py

This is a Python code which provides us with the top 20 news headlines.

Added News Updater code using python

---

Sorting Visualizer/sorting_visualizer.py

Added a sorting visualizer which shows visual representation of bubble, selection and insertion sort.

Added a sorting visualizer

---

Virtual-Mouse/virtual_mouse.py

I have created an AI driven virtual mouse. It works with your hand movement as seen by your webcam. It tracks your hand movement to move the cursor and there's more...pinch your fingers ( thumb and index fingers) to make a click corresponding to left-mouse-button click!

virtual-mouse

---

Calculator/main.py
library project python/main.py

Calculator using tkinter python

---

shuffle deck.py

In this program, you'll learn to shuffle a deck of cards using random module. Our deck is ordered, so we shuffle it using the function shuffle() in random module. Here we have used the standard modules itertools and random that comes with Python.

Python Program to Shuffle Deck of Cards

---

Student-Data-Mgmt/DataMgmt.py

I have uploaded my data management project in response to Issue #53 .

Project added

---

2048 game/2048.py

Added 2048 terminal game written in python.

Added 2048 game

---

Random Story Generator/random_story_generator.py

It will generate a random story.

Adding Random Story Generator

---

Receipt Generator/Reciept_Generator.py

It will generate a receipt of products.

Adding Receipt Generator

---

Textfile analysis/textfile_analysis.py

Adding Text file Analysis Project

Adding Text file Analysis Project

---

Language Translator/Language_translator.py

It can translate in many languages like  "English", "Hindi", "Italian", "Japanese", "Latin", "Malay", "Nepali", "Russian", "Arabic", "Chinese", "Spanish" etc.
Also add it a label of hacktoberfest-accepted to this

Adding Language Translator Project

---

Books Library/main.py

Books Library using python

---

Python Calender/main.py

Future Calender Python script

---

Dice Roll Generator/Dice_Roll_Generator.py

The code was having an error. Happy to help and rectify the error

Fix roll dice

---

Time Series Graph/readme.md
Time Series Graph/time-series-graph.py

I have added a project file- 'Time Series Graph' on python. This is an awesome python project which can enrich the contents of this repository.
Hope you will accept and merge my PR.

Added 'Time Series Graph' Project

---

Hangman Game/HangmanGame.py

Hangman Game

---

Rock,Paper and Scissors.ipynb

A python game in c programming to demonstrate rockpaper scissor game with output

Rock paper scissors 

---

Rock Paper Scissors/rock_paper_scissor.py

@SamarthTMSL added the Rock Paper Scissor game. Can u merge it with a label under hacktoberfest?
**Thank You** ❤️

Rock paper scissor game added

---

auto_clicker using automation/auto_clicker.py
auto_clicker using automation/readme.md
crypto tracker/crypto tracker.py
crypto tracker/readme.md

this is to automate our day today activities

auto_clicker and crypto tracker using python 

---

2050 game.py
Quiz game.py
ball_bounce.py

I added some games by using python

added games

---

planetSimulation/main.py

added a planet simulatot

---

Find Lost Diamon Game/README.md
Find Lost Diamon Game/main.py

simple game run in terminal, find lost diamond

added Find Lost Diamond Game

---

Counting_sort.py

Counting_sort.py

---

Guess the number.py

In this the computer randomly generates a number and you are supposed to guess it

 Guess the number.py

---

image_Processing.py

Please review my pr
Thanks @SamarthTMSL

Add ImageProcessing Project

---

ytdownloader/ytdownloader.py

We can also download the video straight to our google drive using this code just do everything in google colab.
Hey @SamarthTMSL please accept my pr.
Thanks

Add ytdownloader to download youtube video

---

payment form/payment.html

payment form

---

Indian army/first.html

a html file descibing the forces

indian army

---

PokemonGame.py

I made a simple Pyhton prog that selects a pokemone randomly everytime you run it. #15

Pokemon Selector Game
